/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE - edited by Landry Matthews
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "led.h"
#include "orbit_simulator.h"
#include "switch.h"
#include "systick_timer.h"

/*
 * Main method for the Airport Trains project.
 * Flashes LED depending on state of button according to the assignment rubric
 */
int main()
{
	// Initialize systems on the board.
	init_earth_led();
	init_orbit_leds();
	init_switch();
	init_systick();
	init_orbit_state();

	// Kick off the state machine loop
	run_orbit_simulator();
	return 0;
}
